import Head from 'next/head';
import styles from '../styles/Layout.module.css';

export default function Layout({
  headtitle = 'Next app',
  metadescription = 'Generated by create next app',
  children,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{headtitle}</title>
        <meta name="description" content={metadescription} />
      </Head>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          Copright@<b>2022</b>&nbsp;⚡️
        </a>
      </footer>
    </div>
  );
}
